import SessionAuth from "@/components/SessionAuth";
import Navigator from "@/components/Navigator";
import Header from "@/components/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body>
        <SessionAuth>
          <div className="flex h-screen gap-6">
            <div className="flex flex-1 flex-col px-6 sm:px-16">
              <Header />
              {children}
            </div>
          </div>
        </SessionAuth>
      </body>
    </html>
  );
}
